# Generated by Django 3.2.11 on 2022-01-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='date',
            new_name='date_added',
        ),
    ]
